from setuptools import setup

setup(
    name='euron',
    version='0.2',
    packages=['.env.lib.python3.6.distutils', '.env.lib.python3.6.encodings', '.env.lib.python3.6.importlib',
              '.env.lib.python3.6.collections', '.env.lib.python3.6.site-packages.absl',
              '.env.lib.python3.6.site-packages.absl.flags', '.env.lib.python3.6.site-packages.absl.logging',
              '.env.lib.python3.6.site-packages.absl.testing', '.env.lib.python3.6.site-packages.h5py',
              '.env.lib.python3.6.site-packages.h5py._hl', '.env.lib.python3.6.site-packages.h5py.tests',
              '.env.lib.python3.6.site-packages.h5py.tests.hl', '.env.lib.python3.6.site-packages.h5py.tests.old',
              '.env.lib.python3.6.site-packages.pytz', '.env.lib.python3.6.site-packages.PyQt5',
              '.env.lib.python3.6.site-packages.PyQt5.uic', '.env.lib.python3.6.site-packages.PyQt5.uic.Loader',
              '.env.lib.python3.6.site-packages.PyQt5.uic.port_v2',
              '.env.lib.python3.6.site-packages.PyQt5.uic.port_v3',
              '.env.lib.python3.6.site-packages.PyQt5.uic.Compiler', '.env.lib.python3.6.site-packages.keras',
              '.env.lib.python3.6.site-packages.keras.utils', '.env.lib.python3.6.site-packages.keras.engine',
              '.env.lib.python3.6.site-packages.keras.layers', '.env.lib.python3.6.site-packages.keras.legacy',
              '.env.lib.python3.6.site-packages.keras.backend', '.env.lib.python3.6.site-packages.keras.datasets',
              '.env.lib.python3.6.site-packages.keras.wrappers', '.env.lib.python3.6.site-packages.keras.applications',
              '.env.lib.python3.6.site-packages.keras.preprocessing', '.env.lib.python3.6.site-packages.numpy',
              '.env.lib.python3.6.site-packages.numpy.ma', '.env.lib.python3.6.site-packages.numpy.ma.tests',
              '.env.lib.python3.6.site-packages.numpy.doc', '.env.lib.python3.6.site-packages.numpy.fft',
              '.env.lib.python3.6.site-packages.numpy.fft.tests', '.env.lib.python3.6.site-packages.numpy.lib',
              '.env.lib.python3.6.site-packages.numpy.lib.tests', '.env.lib.python3.6.site-packages.numpy.core',
              '.env.lib.python3.6.site-packages.numpy.core.tests', '.env.lib.python3.6.site-packages.numpy.f2py',
              '.env.lib.python3.6.site-packages.numpy.f2py.tests', '.env.lib.python3.6.site-packages.numpy.tests',
              '.env.lib.python3.6.site-packages.numpy.compat', '.env.lib.python3.6.site-packages.numpy.linalg',
              '.env.lib.python3.6.site-packages.numpy.linalg.tests', '.env.lib.python3.6.site-packages.numpy.random',
              '.env.lib.python3.6.site-packages.numpy.random.tests', '.env.lib.python3.6.site-packages.numpy.testing',
              '.env.lib.python3.6.site-packages.numpy.testing.tests',
              '.env.lib.python3.6.site-packages.numpy.testing.nose_tools',
              '.env.lib.python3.6.site-packages.numpy.distutils',
              '.env.lib.python3.6.site-packages.numpy.distutils.tests',
              '.env.lib.python3.6.site-packages.numpy.distutils.command',
              '.env.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              '.env.lib.python3.6.site-packages.numpy.matrixlib',
              '.env.lib.python3.6.site-packages.numpy.matrixlib.tests',
              '.env.lib.python3.6.site-packages.numpy.polynomial',
              '.env.lib.python3.6.site-packages.numpy.polynomial.tests', '.env.lib.python3.6.site-packages.scipy',
              '.env.lib.python3.6.site-packages.scipy.io', '.env.lib.python3.6.site-packages.scipy.io.arff',
              '.env.lib.python3.6.site-packages.scipy.io.arff.tests', '.env.lib.python3.6.site-packages.scipy.io.tests',
              '.env.lib.python3.6.site-packages.scipy.io.matlab',
              '.env.lib.python3.6.site-packages.scipy.io.matlab.tests',
              '.env.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              '.env.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              '.env.lib.python3.6.site-packages.scipy.odr', '.env.lib.python3.6.site-packages.scipy.odr.tests',
              '.env.lib.python3.6.site-packages.scipy._lib', '.env.lib.python3.6.site-packages.scipy._lib.tests',
              '.env.lib.python3.6.site-packages.scipy.misc', '.env.lib.python3.6.site-packages.scipy.misc.tests',
              '.env.lib.python3.6.site-packages.scipy.stats', '.env.lib.python3.6.site-packages.scipy.stats.tests',
              '.env.lib.python3.6.site-packages.scipy.linalg', '.env.lib.python3.6.site-packages.scipy.linalg.tests',
              '.env.lib.python3.6.site-packages.scipy.signal', '.env.lib.python3.6.site-packages.scipy.signal.tests',
              '.env.lib.python3.6.site-packages.scipy.sparse', '.env.lib.python3.6.site-packages.scipy.sparse.tests',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              '.env.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              '.env.lib.python3.6.site-packages.scipy.sparse.csgraph',
              '.env.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              '.env.lib.python3.6.site-packages.scipy.cluster', '.env.lib.python3.6.site-packages.scipy.cluster.tests',
              '.env.lib.python3.6.site-packages.scipy.fftpack', '.env.lib.python3.6.site-packages.scipy.fftpack.tests',
              '.env.lib.python3.6.site-packages.scipy.ndimage', '.env.lib.python3.6.site-packages.scipy.ndimage.tests',
              '.env.lib.python3.6.site-packages.scipy.spatial', '.env.lib.python3.6.site-packages.scipy.spatial.tests',
              '.env.lib.python3.6.site-packages.scipy.special', '.env.lib.python3.6.site-packages.scipy.special.tests',
              '.env.lib.python3.6.site-packages.scipy.special._precompute',
              '.env.lib.python3.6.site-packages.scipy.optimize', '.env.lib.python3.6.site-packages.scipy.optimize._lsq',
              '.env.lib.python3.6.site-packages.scipy.optimize.tests',
              '.env.lib.python3.6.site-packages.scipy.optimize._trlib',
              '.env.lib.python3.6.site-packages.scipy.constants',
              '.env.lib.python3.6.site-packages.scipy.constants.tests',
              '.env.lib.python3.6.site-packages.scipy.integrate',
              '.env.lib.python3.6.site-packages.scipy.integrate._ivp',
              '.env.lib.python3.6.site-packages.scipy.integrate.tests',
              '.env.lib.python3.6.site-packages.scipy.interpolate',
              '.env.lib.python3.6.site-packages.scipy.interpolate.tests',
              '.env.lib.python3.6.site-packages.scipy._build_utils', '.env.lib.python3.6.site-packages.wheel',
              '.env.lib.python3.6.site-packages.wheel.tool', '.env.lib.python3.6.site-packages.wheel.signatures',
              '.env.lib.python3.6.site-packages.bleach', '.env.lib.python3.6.site-packages.google.protobuf',
              '.env.lib.python3.6.site-packages.google.protobuf.util',
              '.env.lib.python3.6.site-packages.google.protobuf.pyext',
              '.env.lib.python3.6.site-packages.google.protobuf.compiler',
              '.env.lib.python3.6.site-packages.google.protobuf.internal',
              '.env.lib.python3.6.site-packages.google.protobuf.internal.import_test_package',
              '.env.lib.python3.6.site-packages.pandas', '.env.lib.python3.6.site-packages.pandas.io',
              '.env.lib.python3.6.site-packages.pandas.io.sas', '.env.lib.python3.6.site-packages.pandas.io.json',
              '.env.lib.python3.6.site-packages.pandas.io.formats',
              '.env.lib.python3.6.site-packages.pandas.io.msgpack',
              '.env.lib.python3.6.site-packages.pandas.io.clipboard', '.env.lib.python3.6.site-packages.pandas.api',
              '.env.lib.python3.6.site-packages.pandas.api.types', '.env.lib.python3.6.site-packages.pandas.core',
              '.env.lib.python3.6.site-packages.pandas.core.util', '.env.lib.python3.6.site-packages.pandas.core.tools',
              '.env.lib.python3.6.site-packages.pandas.core.dtypes',
              '.env.lib.python3.6.site-packages.pandas.core.sparse',
              '.env.lib.python3.6.site-packages.pandas.core.indexes',
              '.env.lib.python3.6.site-packages.pandas.core.reshape',
              '.env.lib.python3.6.site-packages.pandas.core.computation',
              '.env.lib.python3.6.site-packages.pandas.util', '.env.lib.python3.6.site-packages.pandas._libs',
              '.env.lib.python3.6.site-packages.pandas._libs.tslibs', '.env.lib.python3.6.site-packages.pandas.stats',
              '.env.lib.python3.6.site-packages.pandas.tests', '.env.lib.python3.6.site-packages.pandas.tests.io',
              '.env.lib.python3.6.site-packages.pandas.tests.io.sas',
              '.env.lib.python3.6.site-packages.pandas.tests.io.json',
              '.env.lib.python3.6.site-packages.pandas.tests.io.parser',
              '.env.lib.python3.6.site-packages.pandas.tests.io.formats',
              '.env.lib.python3.6.site-packages.pandas.tests.io.msgpack',
              '.env.lib.python3.6.site-packages.pandas.tests.api', '.env.lib.python3.6.site-packages.pandas.tests.util',
              '.env.lib.python3.6.site-packages.pandas.tests.frame',
              '.env.lib.python3.6.site-packages.pandas.tests.tools',
              '.env.lib.python3.6.site-packages.pandas.tests.dtypes',
              '.env.lib.python3.6.site-packages.pandas.tests.scalar',
              '.env.lib.python3.6.site-packages.pandas.tests.series',
              '.env.lib.python3.6.site-packages.pandas.tests.sparse',
              '.env.lib.python3.6.site-packages.pandas.tests.groupby',
              '.env.lib.python3.6.site-packages.pandas.tests.indexes',
              '.env.lib.python3.6.site-packages.pandas.tests.indexes.period',
              '.env.lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              '.env.lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              '.env.lib.python3.6.site-packages.pandas.tests.reshape',
              '.env.lib.python3.6.site-packages.pandas.tests.tseries',
              '.env.lib.python3.6.site-packages.pandas.tests.indexing',
              '.env.lib.python3.6.site-packages.pandas.tests.plotting',
              '.env.lib.python3.6.site-packages.pandas.tests.internals',
              '.env.lib.python3.6.site-packages.pandas.tests.computation',
              '.env.lib.python3.6.site-packages.pandas.tools', '.env.lib.python3.6.site-packages.pandas.types',
              '.env.lib.python3.6.site-packages.pandas.compat', '.env.lib.python3.6.site-packages.pandas.compat.numpy',
              '.env.lib.python3.6.site-packages.pandas.errors', '.env.lib.python3.6.site-packages.pandas.formats',
              '.env.lib.python3.6.site-packages.pandas.tseries', '.env.lib.python3.6.site-packages.pandas.plotting',
              '.env.lib.python3.6.site-packages.pandas.computation', '.env.lib.python3.6.site-packages.sklearn',
              '.env.lib.python3.6.site-packages.sklearn.svm', '.env.lib.python3.6.site-packages.sklearn.svm.tests',
              '.env.lib.python3.6.site-packages.sklearn.tree', '.env.lib.python3.6.site-packages.sklearn.tree.tests',
              '.env.lib.python3.6.site-packages.sklearn.tests', '.env.lib.python3.6.site-packages.sklearn.utils',
              '.env.lib.python3.6.site-packages.sklearn.utils.tests',
              '.env.lib.python3.6.site-packages.sklearn.utils.sparsetools',
              '.env.lib.python3.6.site-packages.sklearn.utils.sparsetools.tests',
              '.env.lib.python3.6.site-packages.sklearn.cluster',
              '.env.lib.python3.6.site-packages.sklearn.cluster.tests',
              '.env.lib.python3.6.site-packages.sklearn.metrics',
              '.env.lib.python3.6.site-packages.sklearn.metrics.tests',
              '.env.lib.python3.6.site-packages.sklearn.metrics.cluster',
              '.env.lib.python3.6.site-packages.sklearn.metrics.cluster.tests',
              '.env.lib.python3.6.site-packages.sklearn.mixture',
              '.env.lib.python3.6.site-packages.sklearn.mixture.tests',
              '.env.lib.python3.6.site-packages.sklearn.datasets',
              '.env.lib.python3.6.site-packages.sklearn.datasets.tests',
              '.env.lib.python3.6.site-packages.sklearn.ensemble',
              '.env.lib.python3.6.site-packages.sklearn.ensemble.tests',
              '.env.lib.python3.6.site-packages.sklearn.manifold',
              '.env.lib.python3.6.site-packages.sklearn.manifold.tests',
              '.env.lib.python3.6.site-packages.sklearn.externals',
              '.env.lib.python3.6.site-packages.sklearn.externals.joblib',
              '.env.lib.python3.6.site-packages.sklearn.neighbors',
              '.env.lib.python3.6.site-packages.sklearn.neighbors.tests',
              '.env.lib.python3.6.site-packages.sklearn.covariance',
              '.env.lib.python3.6.site-packages.sklearn.covariance.tests',
              '.env.lib.python3.6.site-packages.sklearn._build_utils',
              '.env.lib.python3.6.site-packages.sklearn.linear_model',
              '.env.lib.python3.6.site-packages.sklearn.linear_model.tests',
              '.env.lib.python3.6.site-packages.sklearn.__check_build',
              '.env.lib.python3.6.site-packages.sklearn.decomposition',
              '.env.lib.python3.6.site-packages.sklearn.decomposition.tests',
              '.env.lib.python3.6.site-packages.sklearn.preprocessing',
              '.env.lib.python3.6.site-packages.sklearn.preprocessing.tests',
              '.env.lib.python3.6.site-packages.sklearn.neural_network',
              '.env.lib.python3.6.site-packages.sklearn.neural_network.tests',
              '.env.lib.python3.6.site-packages.sklearn.model_selection',
              '.env.lib.python3.6.site-packages.sklearn.model_selection.tests',
              '.env.lib.python3.6.site-packages.sklearn.semi_supervised',
              '.env.lib.python3.6.site-packages.sklearn.semi_supervised.tests',
              '.env.lib.python3.6.site-packages.sklearn.gaussian_process',
              '.env.lib.python3.6.site-packages.sklearn.gaussian_process.tests',
              '.env.lib.python3.6.site-packages.sklearn.feature_selection',
              '.env.lib.python3.6.site-packages.sklearn.feature_selection.tests',
              '.env.lib.python3.6.site-packages.sklearn.feature_extraction',
              '.env.lib.python3.6.site-packages.sklearn.feature_extraction.tests',
              '.env.lib.python3.6.site-packages.sklearn.cross_decomposition',
              '.env.lib.python3.6.site-packages.sklearn.cross_decomposition.tests',
              '.env.lib.python3.6.site-packages.dateutil', '.env.lib.python3.6.site-packages.dateutil.tz',
              '.env.lib.python3.6.site-packages.dateutil.zoneinfo', '.env.lib.python3.6.site-packages.external',
              '.env.lib.python3.6.site-packages.external.absl_py',
              '.env.lib.python3.6.site-packages.external.absl_py.absl',
              '.env.lib.python3.6.site-packages.external.absl_py.absl.flags',
              '.env.lib.python3.6.site-packages.external.six_archive',
              '.env.lib.python3.6.site-packages.external.protobuf_archive',
              '.env.lib.python3.6.site-packages.external.protobuf_archive.python',
              '.env.lib.python3.6.site-packages.external.protobuf_archive.python.google',
              '.env.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf',
              '.env.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf.pyext',
              '.env.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf.compiler',
              '.env.lib.python3.6.site-packages.external.protobuf_archive.python.google.protobuf.internal',
              '.env.lib.python3.6.site-packages.external.org_python_pypi_backports_weakref',
              '.env.lib.python3.6.site-packages.external.org_python_pypi_backports_weakref.backports',
              '.env.lib.python3.6.site-packages.html5lib', '.env.lib.python3.6.site-packages.html5lib.trie',
              '.env.lib.python3.6.site-packages.html5lib.filters',
              '.env.lib.python3.6.site-packages.html5lib.serializer',
              '.env.lib.python3.6.site-packages.html5lib.treewalkers',
              '.env.lib.python3.6.site-packages.html5lib.treeadapters',
              '.env.lib.python3.6.site-packages.html5lib.treebuilders', '.env.lib.python3.6.site-packages.markdown',
              '.env.lib.python3.6.site-packages.markdown.extensions', '.env.lib.python3.6.site-packages.werkzeug',
              '.env.lib.python3.6.site-packages.werkzeug.debug', '.env.lib.python3.6.site-packages.werkzeug.contrib',
              '.env.lib.python3.6.site-packages.setuptools', '.env.lib.python3.6.site-packages.setuptools.extern',
              '.env.lib.python3.6.site-packages.setuptools.command', '.env.lib.python3.6.site-packages.sqlalchemy',
              '.env.lib.python3.6.site-packages.sqlalchemy.ext',
              '.env.lib.python3.6.site-packages.sqlalchemy.ext.declarative',
              '.env.lib.python3.6.site-packages.sqlalchemy.orm', '.env.lib.python3.6.site-packages.sqlalchemy.sql',
              '.env.lib.python3.6.site-packages.sqlalchemy.util', '.env.lib.python3.6.site-packages.sqlalchemy.event',
              '.env.lib.python3.6.site-packages.sqlalchemy.engine',
              '.env.lib.python3.6.site-packages.sqlalchemy.testing',
              '.env.lib.python3.6.site-packages.sqlalchemy.testing.suite',
              '.env.lib.python3.6.site-packages.sqlalchemy.testing.plugin',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects.mssql',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects.mysql',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects.oracle',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects.sqlite',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects.sybase',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects.firebird',
              '.env.lib.python3.6.site-packages.sqlalchemy.dialects.postgresql',
              '.env.lib.python3.6.site-packages.sqlalchemy.databases',
              '.env.lib.python3.6.site-packages.sqlalchemy.connectors', '.env.lib.python3.6.site-packages.tensorflow',
              '.env.lib.python3.6.site-packages.tensorflow.core',
              '.env.lib.python3.6.site-packages.tensorflow.core.lib',
              '.env.lib.python3.6.site-packages.tensorflow.core.lib.core',
              '.env.lib.python3.6.site-packages.tensorflow.core.util',
              '.env.lib.python3.6.site-packages.tensorflow.core.debug',
              '.env.lib.python3.6.site-packages.tensorflow.core.example',
              '.env.lib.python3.6.site-packages.tensorflow.core.grappler',
              '.env.lib.python3.6.site-packages.tensorflow.core.grappler.costs',
              '.env.lib.python3.6.site-packages.tensorflow.core.profiler',
              '.env.lib.python3.6.site-packages.tensorflow.core.protobuf',
              '.env.lib.python3.6.site-packages.tensorflow.core.framework',
              '.env.lib.python3.6.site-packages.tensorflow.tools',
              '.env.lib.python3.6.site-packages.tensorflow.tools.dist_test',
              '.env.lib.python3.6.site-packages.tensorflow.tools.dist_test.server',
              '.env.lib.python3.6.site-packages.tensorflow.tools.pip_package',
              '.env.lib.python3.6.site-packages.tensorflow.tools.graph_transforms',
              '.env.lib.python3.6.site-packages.tensorflow.python',
              '.env.lib.python3.6.site-packages.tensorflow.python.lib',
              '.env.lib.python3.6.site-packages.tensorflow.python.lib.io',
              '.env.lib.python3.6.site-packages.tensorflow.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.python.ops.linalg',
              '.env.lib.python3.6.site-packages.tensorflow.python.ops.losses',
              '.env.lib.python3.6.site-packages.tensorflow.python.ops.distributions',
              '.env.lib.python3.6.site-packages.tensorflow.python.data',
              '.env.lib.python3.6.site-packages.tensorflow.python.data.ops',
              '.env.lib.python3.6.site-packages.tensorflow.python.data.util',
              '.env.lib.python3.6.site-packages.tensorflow.python.util',
              '.env.lib.python3.6.site-packages.tensorflow.python.util.protobuf',
              '.env.lib.python3.6.site-packages.tensorflow.python.debug',
              '.env.lib.python3.6.site-packages.tensorflow.python.debug.cli',
              '.env.lib.python3.6.site-packages.tensorflow.python.debug.lib',
              '.env.lib.python3.6.site-packages.tensorflow.python.debug.examples',
              '.env.lib.python3.6.site-packages.tensorflow.python.debug.wrappers',
              '.env.lib.python3.6.site-packages.tensorflow.python.eager',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.utils',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.engine',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.layers',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.datasets',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.wrappers',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.applications',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras._impl.keras.preprocessing',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.utils',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.layers',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.losses',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.models',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.backend',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.metrics',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets.imdb',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets.mnist',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets.cifar10',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets.reuters',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets.cifar100',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets.fashion_mnist',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.datasets.boston_housing',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.wrappers',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.wrappers.scikit_learn',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.callbacks',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.estimator',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.optimizers',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.activations',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.constraints',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications.vgg16',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications.vgg19',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications.resnet50',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications.xception',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications.mobilenet',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications.inception_v3',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.applications.inception_resnet_v2',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.initializers',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.regularizers',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing.text',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing.image',
              '.env.lib.python3.6.site-packages.tensorflow.python.keras.preprocessing.sequence',
              '.env.lib.python3.6.site-packages.tensorflow.python.tools',
              '.env.lib.python3.6.site-packages.tensorflow.python.client',
              '.env.lib.python3.6.site-packages.tensorflow.python.layers',
              '.env.lib.python3.6.site-packages.tensorflow.python.summary',
              '.env.lib.python3.6.site-packages.tensorflow.python.summary.writer',
              '.env.lib.python3.6.site-packages.tensorflow.python.grappler',
              '.env.lib.python3.6.site-packages.tensorflow.python.platform',
              '.env.lib.python3.6.site-packages.tensorflow.python.profiler',
              '.env.lib.python3.6.site-packages.tensorflow.python.profiler.internal',
              '.env.lib.python3.6.site-packages.tensorflow.python.training',
              '.env.lib.python3.6.site-packages.tensorflow.python.user_ops',
              '.env.lib.python3.6.site-packages.tensorflow.python.estimator',
              '.env.lib.python3.6.site-packages.tensorflow.python.estimator.canned',
              '.env.lib.python3.6.site-packages.tensorflow.python.estimator.export',
              '.env.lib.python3.6.site-packages.tensorflow.python.estimator.inputs',
              '.env.lib.python3.6.site-packages.tensorflow.python.estimator.inputs.queues',
              '.env.lib.python3.6.site-packages.tensorflow.python.framework',
              '.env.lib.python3.6.site-packages.tensorflow.python.saved_model',
              '.env.lib.python3.6.site-packages.tensorflow.python.feature_column',
              '.env.lib.python3.6.site-packages.tensorflow.contrib',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nn.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nn.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.crf',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.crf.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.crf.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.eval',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.eval.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.losses',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.losses.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.features',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.features.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.estimator',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.gan.python.estimator.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.opt',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.opt.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.opt.python.training',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.rnn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.rnn.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.rnn.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.rnn.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.rnn.python.tools',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.rnn.python.kernel_tests',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu.proto',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu.python.tpu',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu.python.profiler',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tpu.profiler',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.data',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.data.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.data.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.kfac',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.kfac.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.kfac.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.lite',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.lite.toco',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.lite.toco.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.lite.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nccl',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nccl.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nccl.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nccl.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.slim',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.slim.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.slim.python.slim',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.slim.python.slim.data',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.slim.python.slim.nets',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.text',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.text.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.text.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.util',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cloud',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cloud.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cloud.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cmake',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cmake.tools',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.proto',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.mnist',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.spinn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.rnn_ptb',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.resnet50',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.rnn_colorbot',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.eager.python.examples.linear_regression',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.hooks',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.hooks.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.hooks.python.training',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.image',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.image.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.image.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.image.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.utils',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.layers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.losses',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.models',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.backend',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.metrics',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.imdb',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.mnist',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar10',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.reuters',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar100',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.datasets.boston_housing',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.wrappers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.wrappers.scikit_learn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.callbacks',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.optimizers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.activations',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.constraints',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg16',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg19',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.resnet50',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.xception',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.mobilenet',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.applications.inception_v3',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.initializers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.regularizers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.text',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.image',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.sequence',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.utils',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.datasets',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.learn_io',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.estimators',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.preprocessing',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.learn.python.learn.preprocessing.tests',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.specs',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.specs.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.ffmpeg',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.ffmpeg.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.layers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.layers.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.layers.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.layers.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.layers.python.layers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.linalg',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.linalg.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.linalg.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.lookup',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.losses',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.losses.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.losses.python.losses',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.losses.python.metric_learning',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.ndlstm',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.ndlstm.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.signal',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.signal.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.signal.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.signal.python.kernel_tests',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tfprof',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.metrics',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.metrics.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.metrics.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.metrics.python.metrics',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.seq2seq',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.seq2seq.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.seq2seq.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.seq2seq.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.solvers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.solvers.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.solvers.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.staging',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.summary',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.testing',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.testing.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.testing.python.framework',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.batching',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.batching.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.batching.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.batching.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.compiler',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.grid_rnn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.grid_rnn.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.grid_rnn.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.quantize',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.quantize.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.training',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.training.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.training.python.training',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.bayesflow',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.bayesflow.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.bayesflow.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cudnn_rnn.python.layers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.estimator',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.estimator.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.estimator.python.estimator',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.framework',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.framework.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.framework.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.framework.python.framework',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.integrate',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.integrate.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.integrate.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.predictor',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.resampler',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.resampler.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.resampler.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.resampler.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.sparsemax',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.sparsemax.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.sparsemax.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.stateless',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.all_reduce',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.all_reduce.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.copy_graph',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.copy_graph.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.copy_graph.python.util',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.deprecated',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.fused_conv',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.fused_conv.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.fused_conv.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.fused_conv.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.timeseries',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.timeseries.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.timeseries.python.timeseries',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.timeseries.python.timeseries.state_space_models',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.timeseries.examples',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.saved_model',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.saved_model.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.saved_model.python.saved_model',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensorboard',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.plugins',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.plugins.trace',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.plugins.projector',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.graph_explorer',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensorboard.graph_explorer.proto',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.graph_editor',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.graph_editor.tests',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.memory_stats',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.memory_stats.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.memory_stats.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.memory_stats.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.quantization',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.quantization.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.lib',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.lib.learner',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.lib.learner.batch',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.proto',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.utils',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.training',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.python.training.functions',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.boosted_trees.estimator_batch',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.distributions',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.distributions.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.distributions.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.distributions.python.ops.bijectors',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.factorization',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.factorization.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.factorization.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.model_pruning',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.model_pruning.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.model_pruning.python.layers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.proto',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.client',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.layers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.models',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.tensor_forest.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.decision_trees',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.decision_trees.proto',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.input_pipeline.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.kernel_methods',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.kernel_methods.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.kernel_methods.python.mappers',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.labeled_tensor',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.labeled_tensor.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.labeled_tensor.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.legacy_seq2seq',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.legacy_seq2seq.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.legacy_seq2seq.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.session_bundle',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.receptive_field',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.receptive_field.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.receptive_field.python.util',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.stat_summarizer',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cluster_resolver',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cluster_resolver.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.cluster_resolver.python.training',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.linear_optimizer',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.linear_optimizer.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.linear_optimizer.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nearest_neighbor',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nearest_neighbor.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.nearest_neighbor.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.reduce_slice_ops.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.periodic_resample',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.periodic_resample.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.periodic_resample.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph.pylib',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python.ops',
              '.env.lib.python3.6.site-packages.tensorflow.contrib.meta_graph_transform',
              '.env.lib.python3.6.site-packages.tensorflow.examples',
              '.env.lib.python3.6.site-packages.tensorflow.examples.tutorials',
              '.env.lib.python3.6.site-packages.tensorflow.examples.tutorials.mnist',
              '.env.lib.python3.6.site-packages.tensorboard', '.env.lib.python3.6.site-packages.tensorboard.backend',
              '.env.lib.python3.6.site-packages.tensorboard.backend.event_processing',
              '.env.lib.python3.6.site-packages.tensorboard.plugins',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.core',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.text',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.audio',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.graph',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.image',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.scalar',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.profile',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.debugger',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.pr_curve',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.histogram',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.projector',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.distribution',
              '.env.lib.python3.6.site-packages.tensorboard.plugins.custom_scalar',
              '.env.lib.python3.6.site-packages.tensorboard.pip_package',
              '.env.lib.python3.6.site-packages.pkg_resources', '.env.lib.python3.6.site-packages.pkg_resources.extern',
              '.env.lib.python3.6.site-packages.pkg_resources._vendor',
              '.env.lib.python3.6.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='Nurlan Musayev',
    author_email='nurlancik1@gmail.com',
    description=''
)
